# docker-compose for local testing
services:
  cell:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    tty: true
    ports:
      - 80:8080
    volumes:
      # Files that are required by runtime
      - ./example:/app/MSConfig
    environment:
    - APP=ms-001
    - K8S_APP=ms-001
    - ZONE=default
    - PN=4
    - TN=16
    - LOG_LEVEL=DEBUG
